---
title: "Investigation of Vaccination Effect on Covid-19 in California"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
    code_folding: hide
    theme: united
    highlight: pygments
---

```{r setup, include=TRUE, cache = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(pomp)
library(tidyverse)
library(doRNG)
library(doParallel)
registerDoParallel()

```



# SEIRDF Model

## Simulation and Guess the parameter

We first use the simulation and try some combinations of estimators to see which combination of estimator will provide a simulation close to the true data. On the plot above, blue line represents the true data, red lines represent the 10 simulated results.

### For Guinea
These simulations are generated by $\beta=17, \beta2=0.8, mu_{EI}=15, mu_{IR}=1.5, mu_{DF}=0.9, F_{size}=50, \rho=0.33, \eta=0.025, N=10628972$. We could see the $\beta2$ is smaller than $beta$, this is because in our model $\beta2$ is divided by the size of funeral, and $beta$ is divided by the whole population of the country, so it is reasonable that $\beta2$ is smaller than $beta$.

### For Sierra Leone
The simulations are generated by $\beta=20, \beta2=1, mu_{EI}=12, mu_{IR}=2, mu_{DF}=1, F_{size}=50, \rho=0.3, \eta=0.025, N=16190280$. And $\beta2$ is smaller for same reason mentioned before.

## Local Search

In the diagnostic plot, the likelihood looks stable, waving between -195 and -190, as the iteration process, while other parameters have large variability. In the plot of the likelihood surface, the loglik plots look so sparse that it does not give us a clear picture or hint of the ridge in likelihood surface. Thus, we move on to do global search.

## Global Search

Similar to the global search above, we first define the range for each parameter based on the knowledge from simulation and local search: $\beta \in [0.008, 0.03], u \in [0.005, 0.03], \sigma \in [0.005, 0.03], \rho \in [0.1,0.4], \eta \in [0.85, 0.95], \mu_{IR} \in [0.0008, 0.03]$.

And the corresponding values the parameters took when the log-likelihood was maximized were:

From the results above, we could see that $\hat{\sigma}_{MLE}$ is `r results_global[which.max(results_global$loglik),"Sigma"]` and the value was quite small, which means that the vaccine was protective against the virus. Also $\hat{\mu}_{VR,MLE}$ was quite large, which means lots of people received full immunity after vaccination. 

## Profile Likelihood For $\beta$

To explore how the log-likelihood changes over different values of $\sigma$, we calculated the profile likelihood of $\sigma$. We chose 20 evenly spaced values between $0.001$ and $0.5$ as the initial values for $\sigma$. Also for each $\sigma$, we uniformly sample a point from the box $\beta \in [0.0001,0.03], \rho \in [0.1,0.6], \eta \in [0.85,0.95], \mu_{IR} \in [0.02,0.1], \mu_{VR} \in [0.1,10]$ as initial value for other parameters. 

The profile log-likelihood for $\sigma$ was shown below

From the plot above, we could see that the maximizer for $\sigma$ was around $0.1$, which was consistent with result from global search. However, we found some flaws in the profile likelihood plot. By Wilk's theorem, we can calculate the $95\%$ confidence interval for log-likelihood, which will be $-190.7 - 0.5 \chi^2_{1,0.95}=-192.62$, which means that as long as the log-liklihood of the models with different values of $\sigma$ are greater than $-192.62$, they will be comparable with the model that has maximum log-likelihood. This fact indicated that maybe parameter $\sigma$ in SIRV model above is weakly identifiable given only the daily new reported cases data.

# Conclusions

In this project, we used SEIRDF model to fit the Ebola data set in Guinea and Sierra Leone. And This is the major conclusion:

+ Need to be done.

# Future works

There are some problems we encountered during this project, which can be done in the future:

+ The dynamics of Ebola cases is very complicated, even though we add death and funeral influence into the model, it still can not fit the data very well. Therefore in the future, we can add more compartments into the model, i.e. people who got quarantined, people who are in countryside or city, to best fit the data.

+ For the SEIRDF model we already get, we simplify the influence of funeral and death without setting delaying period, which means that we have assumption that people have funeral the same day they die. So delaying period also needs to be considered in the future, and it might also has influence on infection of disease.

# References:

1. Course lecture note12-14 https://ionides.github.io/531w21/#class-notes-and-lectures

2. Covid-19 data from COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data

3. Vaccine data from Our World in Data https://ourworldindata.org/coronavirus

4. Masaaki, Ishikawa. “Optimal Strategies for Vaccination Using the Stochastic SIRV Model.” 2012 The Institute of Systems, Control and Information Engineers, 2012, www.jstage.jst.go.jp/article/iscie/25/12/25_343/_article/-char/en.

5. Isam Al-Darabsah, "A time-delayed SVEIR model for imperfect vaccine with a generalized nonmonotone incidence and application to measles", Applied Mathematical Modelling,2021, https://doi.org/10.1016/j.apm.2020.08.084.

6. Sophia Bollag, "California works to track cases of COVID among the vaccinated", https://www.sacbee.com/news/politics-government/capitol-alert/article250705069.html

7. W. K. Wong and Filbert H. Juwono and Tock H. Chua, "SIR Simulation of COVID-19 Pandemic in Malaysia: Will the Vaccination Program be Effective?", arXiv, 2021, https://arxiv.org/abs/2101.07494

8. Ghostine R, Gharamti M, Hassrouny S, Hoteit I. "An Extended SEIR Model with Vaccination for Forecasting the COVID-19 Pandemic in Saudi Arabia Using an Ensemble Kalman Filter." Mathematics. 2021; 9(6):636. https://doi.org/10.3390/math9060636
