---
title: "SEIRF_SierraLeon"
author: "Dylan Glover, Huo Gao, Yili Wang"
date: '2022-04-14'
output: html_document
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
df1 = read.csv(file = 'SL.csv')
```


```{r, message=FALSE}
library(pomp)
library(doParallel)
cores <-  as.numeric(Sys.getenv('SLURM_NTASKS_PER_NODE', unset=NA))
if(is.na(cores)) cores <- detectCores()  
registerDoParallel(cores)

seir_step <- Csnippet("
  double dN_SE = rbinom(S,1-exp(-Beta*I/N*dt)) + rbinom(F_size*F,1-exp(-Beta2/F_size*dt));
  double dN_EI = rbinom(E,1-exp(-mu_EI*dt));
  double dN_IR = rbinom(I,1-exp(-mu_IR*dt));
  double dN_DF = rbinom(F,1-exp(-mu_DF*dt));
  
  S -= dN_SE;
  E += dN_SE - dN_EI;
  I += dN_EI - dN_IR;
  R += round(dN_IR/2);
  D += round(dN_IR/2);
  F = round(dN_IR/2);
  H += dN_IR;
")

seir_rinit <- Csnippet("
  S = nearbyint(eta*N)-935;
  E = 0;
  I = 935;
  R = nearbyint((1-eta)*N);
  F = 0;
  H = 0;
  ")

dmeas <- Csnippet("
double tol = 1.0e-25;

if(reports > 0.0 && H > 0.0)
{
lik = dbinom(reports,H,rho,FALSE) + tol;
} 
else
{
lik = tol;
}
if (give_log) lik = log(lik);

")

rmeas <- Csnippet("

reports = rbinom(H,rho);
if (reports > 0.0) 
{
reports = nearbyint(reports);
} 
else 
{
reports = 0.0;
}
")

ebola = df1 %>%
  select(Date,reports=New_Report) %>%
  pomp(
    times="Date",t0=0,
    rprocess=euler(seir_step,delta.t=1),
    rinit=seir_rinit,
    rmeasure=rmeas,
    dmeasure=dmeas,
    accumvars="H",
    partrans=parameter_trans(
      log=c("Beta","Beta2","mu_EI","mu_IR","mu_DF","F_size"),
      logit=c("rho","eta")
    ),
    paramnames=c("N","Beta","Beta2","mu_EI","mu_IR","mu_DF","F_size","rho","eta"),
    statenames=c("S","E","I","R","D","F","H")
  )
```


```{r}
set.seed(531)
params <- c(Beta=20, Beta2=1, mu_EI=12,mu_IR=2,mu_DF=1,F_size=50,rho=0.3,eta=0.025,N=6190280)

ebola %>%
  simulate(
    params=params,
    nsim=10,format="data.frame",include.data=TRUE
  ) -> sims
sims %>%
  ggplot(aes(x=Date,y=reports,group=.id,color=.id=="data"))+
  geom_line()+
  guides(color="none")+labs(title="Simulation for data")
```

```{r}
params <- c(Beta=20, Beta2=1, mu_EI=12,mu_IR=2,mu_DF=1,F_size=50,rho=0.3,eta=0.025,N=6190280)

foreach(i=1:10,.combine=c) %dopar% {
  library(pomp)
  ebola %>% pfilter(params=params,Np=100)
} -> pf
pf %>% logLik() %>% logmeanexp(se=TRUE) -> L_pf
L_pf
```


#### Local Search

```{r}
# set the random walk parameters
ebola_cooling.fraction.50 <- 0.5
ebola_rw.sd <- rw.sd(
    Beta=0.02,Beta2=0.02,mu_EI=0.02,mu_IR=0.02,mu_DF=0.02,rho=0.02,eta=ivp(0.002)
)

params <- c(Beta=20, Beta2=1, mu_EI=12,mu_IR=2,mu_DF=1,F_size=50,rho=0.3,eta=0.025,N=6190280)

bake(file="local_SL.rds",{
    foreach(i=1:20,.combine=c) %dopar% {
        library(pomp)
        library(tidyverse)
        mif2(ebola,
             params = params,
             Np=2000,
             Nmif=100,
             cooling.fraction.50=ebola_cooling.fraction.50,
             rw.sd=ebola_rw.sd) 
    } -> mifs_local 
    mifs_local
}) -> mifs_local
```

```{r, echo=F}
mifs_local %>%
  traces() %>%
  melt() %>%
  ggplot(aes(x=iteration,y=value,group=L1,color=factor(L1)))+
  geom_line()+
  guides(color="none")+
  facet_wrap(~variable,scales="free_y")
```


```{r}
bake(file="lik_local_SL.rds",{
    foreach(mf=mifs_local,.combine=rbind) %dopar% {
        library(pomp)
        library(tidyverse)
        evals <- replicate(10, logLik(pfilter(mf,Np=5000)))
        ll <- logmeanexp(evals,se=TRUE)
        mf %>% coef() %>% bind_rows() %>% bind_cols(loglik=ll[1],loglik.se=ll[2])
    } -> results
}) -> results
pairs(~loglik+Beta+mu_EI+eta+rho,data=results,pch=16)
```


### Global Search

```{r}
#Beta=20, Beta2=1, mu_EI=12,mu_IR=2,mu_DF=1,F_size=50,rho=0.3,eta=0.025,N=6190280
set.seed(1234567)
fixed_params = c(N=10628972)
runif_design(
    lower=c(Beta=0.0001, Beta2=0.0001, mu_EI=1, mu_IR=0.0001, mu_DF=0.0001, rho=0.0001,eta=0.0001),
    upper=c(Beta=30, Beta2=10, mu_EI=50, mu_IR=2, mu_DF=3, rho=0.9,eta=0.5),
    nseq=400
) -> guesses
mf1 <- mifs_local[[1]]


bake(file="global_SL.rds",{
    foreach(guess=iter(guesses,"row"), .combine=rbind) %dopar% {
        library(pomp)
        library(tidyverse)
        mf1 %>%
            mif2(params=c(guess,fixed_params)) %>%
            mif2(Nmif=200) -> mf
        replicate(
            10,
            mf %>% pfilter(Np=10000) %>% logLik()
        ) %>%
            logmeanexp(se=TRUE) -> ll
        mf %>% coef() %>% bind_rows() %>%
            bind_cols(loglik=ll[1],loglik.se=ll[2])
    } -> results
    results
}) -> results

results %>%
  bind_rows(results) %>%
  filter(is.finite(loglik)) %>%
  arrange(-loglik) %>%
  write_csv("SL_params.csv")
  
```


```{r}
read_csv("SL_params.csv") %>%
    filter(loglik>max(loglik)-50) %>%
    bind_rows(guesses) %>%
    mutate(type=if_else(is.na(loglik),"guess","result")) %>%
    arrange(type) -> all
pairs(~loglik+Beta+mu_EI+eta+rho, data=all, pch=16, cex=0.3, col=ifelse(all$type=="guess",grey(0.5),"red"))

```

```{r}
read_csv("SL_params.csv") %>%
    group_by(cut=round(Beta,2)) %>%
    filter(rank(-loglik)<=10) %>%
    ungroup() %>%
    arrange(-loglik) %>%
    select(-cut,-loglik,-loglik.se) -> guesses

bake(file="beta_SL.rds",{
    foreach(guess=iter(guesses,"row"), .combine=rbind) %dopar% {
        library(pomp)
        library(tidyverse)
        mf1 %>%
            mif2(params=guess,fixed_params,
                 rw.sd=rw.sd(Beta2=0.02,mu_EI=0.02,mu_IR=0.02,mu_DF=0.02,rho=0.02,eta=ivp(0.002))) %>%
            mif2(Nmif=100,cooling.fraction.50=0.3) %>%
            mif2() -> mf
        replicate(
            10,
            mf %>% pfilter(Np=5000) %>% logLik()) %>%
            logmeanexp(se=TRUE) -> ll
        mf %>% coef() %>% bind_rows() %>%
            bind_cols(loglik=ll[1],loglik.se=ll[2])
    } -> results
}) -> results

read_csv("SL_params.csv") %>%
    bind_rows(results) %>%
    filter(is.finite(loglik)) %>%
    arrange(-loglik) %>%
    write_csv("SL_params.csv")

results %>%
    filter(is.finite(loglik)) -> results
pairs(~loglik+Beta+mu_EI+eta+rho,data=results,pch=16)

results %>%
    filter(loglik>max(loglik)-10,loglik.se<1) %>%
    group_by(round(Beta,2)) %>%
    filter(rank(-loglik)<3) %>%
    ungroup() %>%
    ggplot(aes(x=Beta,y=loglik))+
    geom_point()+
    geom_hline(color="red",yintercept=max(results$loglik)-0.5*qchisq(df=1,p=0.95)
    )

results %>%
    filter(loglik>max(loglik)-0.5*qchisq(df=1,p=0.95)) %>%
    summarize(min=min(Beta),max=max(Beta)) -> beta_SL_ci
beta_SL_ci
```

### References
https://journalhss.com/wp-content/uploads/jhss_51_073-090.pdf